-- ==============================================================================
-- MIGRAÇÃO: MÓDULO DE GESTÃO DE TUNAGENS E REPASSE FINANCEIRO ENTRE MECÂNICAS
-- ==============================================================================

-- 1. TABELA DE MECÂNICAS / OFICINAS CADASTRADAS NA CIDADE
CREATE TABLE IF NOT EXISTS mecanicas (
  id TEXT PRIMARY KEY,
  nome TEXT NOT NULL,
  cor TEXT DEFAULT '#ec4899',
  icone TEXT DEFAULT '🛠️',
  ativo BOOLEAN DEFAULT TRUE,
  criado_em TIMESTAMPTZ DEFAULT NOW()
);

-- Inserir mecânicas padrão caso não existam
INSERT INTO mecanicas (id, nome, cor, icone) VALUES
  ('reds', 'RED''s Tunershop', '#ef4444', '🔴'),
  ('dudark', 'Dudark Motors', '#eab308', '🟡'),
  ('harmony', 'Harmony Custom', '#3b82f6', '🔵'),
  ('vespucci', 'Vespucci Tunershop', '#8b5cf6', '🟣'),
  ('policia', 'Departamento de Polícia', '#06b6d4', '🚓'),
  ('outros', 'Outros', '#64748b', '🏢')
ON CONFLICT (id) DO UPDATE SET
  nome = EXCLUDED.nome,
  cor = EXCLUDED.cor,
  icone = EXCLUDED.icone;

-- 2. TABELA DE VÍNCULOS E HISTÓRICO DE MECÂNICOS (QUADRO DE FUNCIONÁRIOS)
CREATE TABLE IF NOT EXISTS mecanicos_vinculos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mecanico_id TEXT NOT NULL,
  mecanico_nome TEXT NOT NULL,
  cargo TEXT,
  mecanica_id TEXT NOT NULL REFERENCES mecanicas(id) ON DELETE CASCADE,
  data_inicio DATE NOT NULL,
  data_fim DATE,
  ativo BOOLEAN DEFAULT TRUE,
  criado_em TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mecanicos_vinculos_id ON mecanicos_vinculos(mecanico_id);
CREATE INDEX IF NOT EXISTS idx_mecanicos_vinculos_mecanica ON mecanicos_vinculos(mecanica_id);
CREATE INDEX IF NOT EXISTS idx_mecanicos_vinculos_periodo ON mecanicos_vinculos(data_inicio, data_fim);

-- 3. TABELA DE LOGS DE TUNAGEM DE VEÍCULOS
CREATE TABLE IF NOT EXISTS logs_tunagem (
  uuid TEXT PRIMARY KEY,
  tecnico_id TEXT NOT NULL,
  tecnico_nome TEXT NOT NULL,
  dono_id TEXT,
  dono_nome TEXT,
  veiculo_nome TEXT,
  veiculo_modelo TEXT,
  placa TEXT,
  valor_pago NUMERIC NOT NULL DEFAULT 0,
  antes_json JSONB,
  depois_json JSONB,
  data DATE NOT NULL,
  hora TIME NOT NULL,
  timestampz TIMESTAMPTZ,
  raw_text TEXT,
  criado_em TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_logs_tunagem_tecnico ON logs_tunagem(tecnico_id);
CREATE INDEX IF NOT EXISTS idx_logs_tunagem_data ON logs_tunagem(data);
CREATE INDEX IF NOT EXISTS idx_logs_tunagem_placa ON logs_tunagem(placa);
