-- ==============================================================================
-- CRIAÇÃO DA TABELA DE OUVIDORIA & FEEDBACKS DA EQUIPE (RED'S TUNERSHOP)
-- Execute este script no SQL Editor do seu Supabase:
-- https://supabase.com/dashboard/project/prperurjtvayjrazdxvh/sql/new
-- e/ou no banco novo:
-- https://supabase.com/dashboard/project/sxrfkbjbyjdmyyxbzobb/sql/new
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.feedbacks_equipe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    usuario_nome TEXT,
    usuario_cargo TEXT,
    anonimo BOOLEAN DEFAULT FALSE,
    categoria TEXT NOT NULL, -- 'dificuldades', 'estoque', 'atendimento', 'interno', 'sugestoes'
    mensagem TEXT NOT NULL,
    status TEXT DEFAULT 'pendente', -- 'pendente', 'em_analise', 'resolvido'
    resposta_admin TEXT,
    respondido_por TEXT,
    respondido_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para buscas rápidas
CREATE INDEX IF NOT EXISTS idx_feedbacks_categoria ON public.feedbacks_equipe (categoria);
CREATE INDEX IF NOT EXISTS idx_feedbacks_criado_em ON public.feedbacks_equipe (criado_em DESC);
CREATE INDEX IF NOT EXISTS idx_feedbacks_status ON public.feedbacks_equipe (status);

-- Habilitar RLS (Permitir leitura/escrita pública ou autenticada)
ALTER TABLE public.feedbacks_equipe ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir inserção de feedbacks para todos" 
ON public.feedbacks_equipe FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Permitir leitura de feedbacks para todos" 
ON public.feedbacks_equipe FOR SELECT 
USING (true);

CREATE POLICY "Permitir atualização de feedbacks para todos" 
ON public.feedbacks_equipe FOR UPDATE 
USING (true);
