-- ==============================================================================
-- CRIAÇÃO DAS TABELAS DO BLOCO 1 (Sistema / Operação) e BLOCO 2 (RH / Recrutamento)
-- Execute este script no SQL Editor do seu novo Supabase:
-- https://supabase.com/dashboard/project/sxrfkbjbyjdmyyxbzobb/sql/new
-- ==============================================================================

-- 1. configuracoes
CREATE TABLE IF NOT EXISTS public.configuracoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quadro_avisos JSONB,
    canais_bot JSONB,
    fardas JSONB
);

-- 2. curso_configuracoes
CREATE TABLE IF NOT EXISTS public.curso_configuracoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo BOOLEAN DEFAULT TRUE,
    permissoes JSONB,
    modulos JSONB,
    atualizado_em TIMESTAMPTZ,
    atualizado_por BIGINT
);

-- 3. clientes
CREATE TABLE IF NOT EXISTS public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT,
    total_gasto NUMERIC DEFAULT 0,
    ultima_alteracao TIMESTAMPTZ,
    data_ultimo_servico TIMESTAMPTZ
);

-- 4. servicos
CREATE TABLE IF NOT EXISTS public.servicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id BIGINT,
    funcionario_nome TEXT,
    cliente_id BIGINT,
    cliente_nome TEXT,
    tipo TEXT,
    valor_total NUMERIC,
    data DATE,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    link_imagem TEXT,
    detalhes TEXT
);

-- 5. pagamentos_semanais
CREATE TABLE IF NOT EXISTS public.pagamentos_semanais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id BIGINT,
    funcionario_nome TEXT,
    valor NUMERIC,
    observacao TEXT,
    confirmado BOOLEAN DEFAULT FALSE,
    confirmado_por BIGINT,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    confirmado_em TIMESTAMPTZ,
    comprovante_link TEXT
);

-- 6. vendas_nitro
CREATE TABLE IF NOT EXISTS public.vendas_nitro (
    id TEXT PRIMARY KEY,
    cliente_id BIGINT,
    cliente_nome TEXT,
    mecanico_id BIGINT,
    mecanico_nome TEXT,
    valor NUMERIC,
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 7. vendas_nitro_cidade
CREATE TABLE IF NOT EXISTS public.vendas_nitro_cidade (
    id TEXT PRIMARY KEY,
    id_jogo BIGINT,
    nome_personagem TEXT,
    quantidade INTEGER DEFAULT 1,
    preco TEXT,
    data_compra TIMESTAMPTZ,
    uuid_log TEXT,
    link_venda TEXT,
    acao TEXT,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    importado_por BIGINT,
    link_bancada TEXT
);

-- 8. vendas_drift_cidade
CREATE TABLE IF NOT EXISTS public.vendas_drift_cidade (
    id TEXT PRIMARY KEY,
    id_jogo BIGINT,
    nome_personagem TEXT,
    item_key TEXT,
    item_name TEXT,
    quantidade INTEGER DEFAULT 1,
    preco TEXT,
    data_compra TIMESTAMPTZ,
    uuid_log TEXT,
    link_venda TEXT,
    acao TEXT,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    importado_por BIGINT
);

-- 9. notificacoes
CREATE TABLE IF NOT EXISTS public.notificacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT,
    admin_nome TEXT,
    funcionario_id BIGINT,
    funcionario_nome TEXT,
    mensagem TEXT,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    lido_em TIMESTAMPTZ,
    anonimo BOOLEAN DEFAULT FALSE,
    admin_id_real BIGINT
);

-- 10. config_vagas
CREATE TABLE IF NOT EXISTS public.config_vagas (
    area_id TEXT PRIMARY KEY,
    ativa BOOLEAN DEFAULT TRUE
);

-- 11. candidaturas
CREATE TABLE IF NOT EXISTS public.candidaturas (
    id TEXT PRIMARY KEY,
    usuario_id BIGINT,
    usuario_nome TEXT,
    area TEXT,
    area_titulo TEXT,
    carta_apresentacao TEXT,
    justificativa TEXT,
    status TEXT,
    feedback_admin TEXT,
    analisado_por BIGINT,
    analisado_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 12. blacklist
CREATE TABLE IF NOT EXISTS public.blacklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passaporte TEXT,
    motivo TEXT,
    criado_por TEXT,
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- HABILITAR RLS E POLÍTICAS PERMISSIVAS
-- ==============================================================================

ALTER TABLE public.configuracoes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir tudo na tabela configuracoes" ON public.configuracoes;
CREATE POLICY "Permitir tudo na tabela configuracoes" ON public.configuracoes FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.curso_configuracoes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir tudo na tabela curso_configuracoes" ON public.curso_configuracoes;
CREATE POLICY "Permitir tudo na tabela curso_configuracoes" ON public.curso_configuracoes FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir tudo na tabela clientes" ON public.clientes;
CREATE POLICY "Permitir tudo na tabela clientes" ON public.clientes FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.servicos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir tudo na tabela servicos" ON public.servicos;
CREATE POLICY "Permitir tudo na tabela servicos" ON public.servicos FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.pagamentos_semanais ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir tudo na tabela pagamentos_semanais" ON public.pagamentos_semanais;
CREATE POLICY "Permitir tudo na tabela pagamentos_semanais" ON public.pagamentos_semanais FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.vendas_nitro ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir tudo na tabela vendas_nitro" ON public.vendas_nitro;
CREATE POLICY "Permitir tudo na tabela vendas_nitro" ON public.vendas_nitro FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.vendas_nitro_cidade ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir tudo na tabela vendas_nitro_cidade" ON public.vendas_nitro_cidade;
CREATE POLICY "Permitir tudo na tabela vendas_nitro_cidade" ON public.vendas_nitro_cidade FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.vendas_drift_cidade ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir tudo na tabela vendas_drift_cidade" ON public.vendas_drift_cidade;
CREATE POLICY "Permitir tudo na tabela vendas_drift_cidade" ON public.vendas_drift_cidade FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.notificacoes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir tudo na tabela notificacoes" ON public.notificacoes;
CREATE POLICY "Permitir tudo na tabela notificacoes" ON public.notificacoes FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.config_vagas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir tudo na tabela config_vagas" ON public.config_vagas;
CREATE POLICY "Permitir tudo na tabela config_vagas" ON public.config_vagas FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.candidaturas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir tudo na tabela candidaturas" ON public.candidaturas;
CREATE POLICY "Permitir tudo na tabela candidaturas" ON public.candidaturas FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.blacklist ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir tudo na tabela blacklist" ON public.blacklist;
CREATE POLICY "Permitir tudo na tabela blacklist" ON public.blacklist FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- ADICIONAR AO REALTIME (Para atualizações instantâneas no front-end)
-- ==============================================================================
DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.configuracoes;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.curso_configuracoes;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.clientes;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.servicos;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.pagamentos_semanais;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.vendas_nitro;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.vendas_nitro_cidade;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.vendas_drift_cidade;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.notificacoes;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.config_vagas;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.candidaturas;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.blacklist;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;
